### ISSUE TITLE
Jobs Resource

### ISSUE THREAD

**Issue by michaellennox** [michaellennox/jobber#70]
- [x] User flows for people resource
- [x] jobsResourceFactory + unit tests
- [x] newJobCtrl + unit tests + HTML partial
- [x] viewJobCtrl + unit tests + HTML partial
- [x] Protractor test for creating a job
- [x] Server: DB Schema & Model for Job, many jobs to one company, associate on both ends
- [x] Server: POST route for /companies/:id/jobs + acceptance tests
- [x] Server: GET route for /companies/:company_id/jobs/:id + acceptance tests

**Comment by Adzz** [comment]
Resource contents:

-pay
-term: temp / permanent/ freelance full time
-key perks
- working hours
